name: Deploy Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
      pages: 'write'
      actions: 'write'
      checks: 'write'
      deployments: 'write'
    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install Pnpm
      run: npm install pnpm -g

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build the app
      run: pnpm run build:docs
    - name: Run test
      run: pnpm run test
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: './packages/docs/.vitepress/dist'

  deploy:
    name: Deploy to github page
    runs-on: ubuntu-latest
    
    steps:
    - name: Download docs
      id: deployment
      uses: actions/download-artifact@v4
      with:
        name: docs
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:  
        GITHUB_TOKEN: ${{ secrets.GUJIAM_PAGES }}
        publish_dir: .
